- name: Comment ScheduleControllerIntegrationTest
  ansible.builtin.replace:
    path: "/home/{{ ansible_user }}/eSchool/src/test/java/academy/softserve/eschool/controller/ScheduleControllerIntegrationTest.java"
    regexp: '^'
    replace: '// '
  ignore_errors: true

#application_properties configuration changing
- name: Update spring.datasource.url
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/eSchool/src/main/resources/application.properties"
    regexp: '^spring.datasource.url='
    line: "spring.datasource.url=jdbc:mysql://{{ mysql_host }}:3306/eschool"

- name: Update spring.datasource.username
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/eSchool/src/main/resources/application.properties"
    regexp: '^spring.datasource.username='
    line: "spring.datasource.username={{ mysql_user }}"

- name: Update spring.datasource.password
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/eSchool/src/main/resources/application.properties"
    regexp: '^spring.datasource.password='
    line: "spring.datasource.password={{ mysql_password }}"

- name: Clean project
  ansible.builtin.command: mvn clean
  args:
    chdir: "/home/{{ ansible_user }}/eSchool"

- name: Build project 
  ansible.builtin.command: mvn install -DskipTests
  args:
    chdir: "/home/{{ ansible_user }}/eSchool"
  register: maven_build

- name: Ensure target and logs directories exist
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/eSchool/target/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - ""       
    - "logs"   

- import_tasks: systemd.yaml

- name: Wait for application jar file
  ansible.builtin.wait_for:
    path: "/home/{{ ansible_user }}/eSchool/target/eschool.jar"
    state: present
    timeout: 300

# - name: Allow HTTP port 8080 in firewall
#   ansible.builtin.ufw:
#     rule: allow
#     port: 8080
#     proto: tcp

- name: Ensure eSchool service is reloaded, enabled and started
  ansible.builtin.systemd:
    name: eschool.service
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Wait for application to start on port 8080
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 8080
    state: started
    timeout: 60
