- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Install Maven
  apt:
    name: maven
    state: present

- name: Install Git
  apt:
    name: git
    state: present

- name: Clone eSchool repository
  git:
    repo: https://github.com/yurkovskiy/eSchool
    dest: /home/{{ ansible_user }}/eSchool
